### ISSUE TITLE
Optional fallback if app is not available

### ISSUE THREAD

**Issue by blakewood84** [mohn93/app_linkster#1]
Hey Mohaned! Thank you for creating this package! It's very helpful!

I was wondering if it's possible to create a fallback here somehow if the app is not installed on the phone. I would love to launch a native browser instead of an inapp web view using url_launcher or something.

Thank you for your time! Blessings!

**Comment by mohn93** [comment]
Hello, thanks for trying out the package

Sounds good, will add this feature right away

**Comment by blakewood84** [comment]
@mohn93 Thank you! 🤩 That means a lot!

**Comment by blakewood84** [comment]
Let me know if there's anything I can help with!

**Comment by mohn93** [comment]
@blakewood84  Pushed Version 0.0.5, the launch method now takes a fallbackLaunchMode param, you can check for it's documentation

if you think this doesn't solve your problem please feel free to reopen the issue
